@startuml
start
:Установка ПО на ноутбук;
:Установка ПО на смартфон;
:Настройки точки доступа на смартфоне;
:Подключение к точке доступа с ноутбука;
split
partition "**Измерение RTT**" {
while (3 раза выполнили тест?)
  fork
    :Сгенерировать низкоскоростной\nTCP-траффик с iperf;
  fork again
    :Сохранить TCP-траффик\nс помощью tcpdump;
    :Посчитать\nмин/макс/среднее\nс помощью tshark;
    :Сгенерировать график\nизменения RTT\nс помощью wireshark;
  end merge
  :Внести результаты в отчет;
  :Посчитать\nмин/макс/среднее\nпо всем тестам;
end while
}
split again
partition "**Измерение скорости**" {
  while (3 раза выполнили тесты?)
    split
      :Сгенерировать\nTCP-траффик;  
    split again
      :Сгенерировать\nUDP-траффик,\nотправитель ноутбук;  
    split again
      :Сгенерировать\nUDP-траффик,\nотправитель смартфон;
    end split
    :Внести промежуточные\nрезультаты в отчет;
  end while
  :Посчитать\nмин/макс/среднее\nпо всем тестам;
}
end split
:Заполнение отчета;
stop
@enduml