@startuml

!include <office/Devices/cell_phone_android_proportional>
!include <office/Devices/device_laptop>

title Топология сети для эксперимента
nwdiag {
    network WLAN_2_4 {
        description = "WLAN 2.4GHz";
        address = "192.168.211.0/24";
        laptop [address = "192.168.211.58, 08:00:27:f9:67:ab", description = "<$device_laptop>\nВМ\nDebian 11"];
        mobile_phone [address = "192.168.211.125, d6:36:e3:d2:69:a0", description = "<$cell_phone_android_proportional>\nAndroid\nСмартфон"];
    }
}

@enduml
