@startuml

!include <office/Devices/cell_phone_android_proportional>
!include <office/Devices/device_laptop>

title Топология сети для эксперимента
nwdiag {
    network WLAN_2_4 {
        description = "WLAN 2.4GHz";
        address = "192.168.211.0/24, 300 Mbps";
        laptop [address = "192.168.211.58, 08:00:27:F9:67:AB", description = "<$device_laptop>\nНоутбук\nDebian 11"];
        mobile_phone [address = "192.168.211.125, ", description = "<$cell_phone_android_proportional>\nAndroid\nСмартфон"];
    }
}

@enduml
